export enum Mangle {
  SESSION_TOKEN = '_nbst',
  PATIENT_PERSONAL_INFO = '_ppi',
  PATIENT_CONTACT_INFO = '_pci',
  PATIENT_INSURANCE_INFO = '_pii',
  PATIENT_CURRENT_FORM = '_pcf',
  NOTIFY_PROMPT_TIMER = 'nbt_npt',
  FCM_TOKEN = 'fcmToken::id'
}

export enum EnumPatientForm {
  PEROSNAL = Mangle.PATIENT_PERSONAL_INFO,
  CONTACT = Mangle.PATIENT_CONTACT_INFO,
  INSURANCE = Mangle.PATIENT_INSURANCE_INFO
}

export enum EnumRole {
  ALL = 'ALL',
  SUPER_ADMIN = 'SUPER_ADMIN',
  DOCTOR = 'DOCTOR',
  REFERRAL_DOCTOR = 'REFERRAL_DOCTOR',
  PATIENT = 'PATIENT',
  LAB_CORDINATOR = 'LAB_CORDINATOR',
  LAB_TECHNICIAN = 'LAB_TECHNICIAN',
  RECEPTIONIST = 'RECEPTIONIST',
  MARKETER = 'MARKETER',
  TECHNICAL_COORDINATOR = 'TECHNICAL_COORDINATOR'
}

export enum EnumUserStatus {
  ACTIVE = 'active',
  INACTIVE = 'inactive',
  INVITED = 'invited',
  SUSPENDED = 'suspended',
  AVAILABLE = 'Available',
  UNAVAILABLE = 'Unavailable'
}

export enum EnumTestLocation {
  CUSTOM = 'Custom',
  LAB = 'Lab'
}

export enum EnumNotificationType {
  // ===== PATIENT NOTIFICATIONS =====
  // Appointment related
  APPOINTMENT_CREATED = 'APPOINTMENT_CREATED',
  APPOINTMENT_CONFIRMED = 'APPOINTMENT_CONFIRMED',
  APPOINTMENT_RESCHEDULED = 'APPOINTMENT_RESCHEDULED',
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',

  // Test related
  TEST_RESULT_READY = 'TEST_RESULT_READY',
  TEST_SAMPLE_COLLECTED = 'TEST_SAMPLE_COLLECTED',
  TEST_IN_PROGRESS = 'TEST_IN_PROGRESS',
  TEST_COMPLETED = 'TEST_COMPLETED',

  // Payment related
  PAYMENT_SUCCESSFUL = 'PAYMENT_SUCCESSFUL',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',
  BILLING_REMINDER = 'BILLING_REMINDER',

  // Profile & Account
  PROFILE_UPDATED = 'PROFILE_UPDATED',
  ACCOUNT_VERIFIED = 'ACCOUNT_VERIFIED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',

  // ===== LAB COORDINATOR NOTIFICATIONS =====
  // Test Management
  NEW_TEST_REQUEST = 'NEW_TEST_REQUEST',
  TEST_ASSIGNED = 'TEST_ASSIGNED',
  TEST_REASSIGNED = 'TEST_REASSIGNED',
  TEST_QUALITY_CONTROL_PENDING = 'TEST_QUALITY_CONTROL_PENDING',
  TEST_QUALITY_CONTROL_PASSED = 'TEST_QUALITY_CONTROL_PASSED',
  TEST_QUALITY_CONTROL_FAILED = 'TEST_QUALITY_CONTROL_FAILED',

  // Quality Control
  QC_TEST_PENDING = 'QC_TEST_PENDING',
  QC_TEST_COMPLETED = 'QC_TEST_COMPLETED',
  QC_TEST_FAILED = 'QC_TEST_FAILED',

  // ===== LAB TECHNICIAN NOTIFICATIONS =====
  // Test Assignment
  TEST_ASSIGNED_TO_TECHNICIAN = 'TEST_ASSIGNED_TO_TECHNICIAN',
  TEST_REASSIGNED_TO_TECHNICIAN = 'TEST_REASSIGNED_TO_TECHNICIAN',
  URGENT_TEST_ASSIGNED = 'URGENT_TEST_ASSIGNED',

  // Test Processing
  TEST_COMPLETION_REMINDER = 'TEST_COMPLETION_REMINDER',
  TEST_DEADLINE_APPROACHING = 'TEST_DEADLINE_APPROACHING',
  TEST_OVERDUE = 'TEST_OVERDUE',

  // Staff Coordination
  DOCTOR_AVAILABILITY_CHANGED = 'DOCTOR_AVAILABILITY_CHANGED',
  STAFF_ABSENCE_NOTIFIED = 'STAFF_ABSENCE_NOTIFIED',

  // ===== MARKETER NOTIFICATIONS =====
  TEST_ASSIGNED_TO_MARKETER = 'TEST_ASSIGNED_TO_MARKETER',
  UPLOAD_SAMPLE_COMPLETED = 'UPLOAD_SAMPLE_COMPLETED',

  // ===== DOCTORS NOTIFICATIONS =====
  DOCTOR_APPOINTMENT_REQUEST = 'DOCTOR_APPOINTMENT_REQUEST',
  DOCTOR_REFERRALS = 'DOCTOR_REFERRALS',
  DOCTOR_TEST_RESULT_READY = 'DOCTOR_TEST_RESULT_READY',
  DOCTOR_TEST_SAMPLE_COLLECTED = 'DOCTOR_TEST_SAMPLE_COLLECTED',
  DOCTOR_TEST_IN_PROGRESS = 'DOCTOR_TEST_IN_PROGRESS',
  DOCTOR_TEST_COMPLETED = 'DOCTOR_TEST_COMPLETED',
  DOCTOR_RECOMMENDATIONS = 'DOCTOR_RECOMMENDATIONS'
}

export enum EnumAdminContentMgt {
  BLOG = 'blog',
  TESTS = 'tests',
  PRODUCTS = 'products',
  HERO = 'hero',
  TESTIMONIALS = 'testimonials',
  FAQ = 'faq',
  ABOUT = 'about',
  CONTACT = 'contact',
  PARTNERS = 'partners',
  DOCTORS_FEE = 'doctors-fee'
}

export enum EnumMediaVisibilityStatus {
  PUBLIC = 'PUBLIC',
  PRIVATE = 'PRIVATE'
}
